const piprLogoUrl = "https://pipr.run/apple-touch-icon.png";
const piprRepositoryUrl = "https://github.com/somus/pipr";

export const mainCommentTitle = `# <img src="${piprLogoUrl}" width="22" height="22" alt=""> Pipr Review`;

const legacyMainCommentTitles = new Set(["# pipr Review", "# Pipr Review", mainCommentTitle]);

const mainCommentAttributionPattern =
  /^<sub>Review generated by \[Pipr\]\(https:\/\/github\.com\/somus\/pipr\) for commit `[^`]+`\.<\/sub>$/;

export function renderMainCommentAttribution(reviewedHeadSha: string): string {
  return `<sub>Review generated by [Pipr](${piprRepositoryUrl}) for commit \`${reviewedHeadSha.slice(
    0,
    7,
  )}\`.</sub>`;
}

export function isMainCommentTitle(line: string): boolean {
  return legacyMainCommentTitles.has(line);
}

export function isMainCommentAttribution(line: string): boolean {
  return mainCommentAttributionPattern.test(line);
}
