const piprLogoUrl = "https://pipr.run/apple-touch-icon.png";
export const piprRepositoryUrl = "https://github.com/somus/pipr";

export const mainCommentTitle = `# <img src="${piprLogoUrl}" width="22" height="22" alt=""> Pipr Review`;

export const mainCommentTitles = new Set(["# pipr Review", "# Pipr Review", mainCommentTitle]);

const escapedRepositoryUrl = piprRepositoryUrl.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export const mainCommentAttributionPattern = new RegExp(
  `^<sub>Review generated by \\[Pipr\\]\\(${escapedRepositoryUrl}\\) for commit \`[^\`]+\`\\.</sub>$`,
);
