const piprLogoUrl = "https://pipr.run/apple-touch-icon.png";
export const piprRepositoryUrl = "https://github.com/somus/pipr";

export const mainCommentTitle = `# <img src="${piprLogoUrl}" width="22" height="22" alt=""> Pipr Review`;

export const mainCommentTitles = new Set(["# pipr Review", "# Pipr Review", mainCommentTitle]);

export const mainCommentAttributionPattern =
  /^<sub>Review generated by \[Pipr\]\(https:\/\/github\.com\/somus\/pipr\) for commit `[^`]+`\.<\/sub>$/;
