import { describe, expect, it } from "bun:test";
import type { DiffManifest, ReviewFinding } from "../../types.js";
import {
  buildPublicationPlan,
  prepareInlinePublicationItems,
  publicationPlanForHostCapabilities,
  runtimeVersion,
} from "../comment.js";
import { mainCommentTitle } from "../comment-branding.js";
import {
  applyInlineFindingMarkers,
  buildPriorReviewState,
  extractInlineFindingMarkers,
  extractPriorReviewState,
} from "../prior-state.js";
import { priorReviewForTask } from "../task/task-output.js";

const finding: ReviewFinding = {
  body: "This can fail.",
  path: "src/a.ts",
  rangeId: "range-1",
  side: "RIGHT",
  startLine: 10,
  endLine: 10,
  suggestedFix: "Use a safe call.",
};

const manifest: DiffManifest = {
  baseSha: "base",
  headSha: "head",
  mergeBaseSha: "base",
  files: [
    {
      path: "src/a.ts",
      status: "modified",
      additions: 1,
      deletions: 0,
      hunks: [
        {
          hunkIndex: 1,
          header: "@@ -10,1 +10,1 @@",
          oldStart: 10,
          oldLines: 1,
          newStart: 10,
          newLines: 1,
          contentHash: "deadbeefcafe",
        },
      ],
      commentableRanges: [
        {
          id: "range-1",
          path: "src/a.ts",
          side: "RIGHT",
          startLine: 10,
          endLine: 10,
          kind: "added",
          hunkIndex: 1,
          hunkHeader: "@@ -10,1 +10,1 @@",
          hunkContentHash: "deadbeefcafe",
          preview: "fail()",
        },
      ],
    },
  ],
};

const event = {
  change: {
    number: 1,
    title: "",
    description: "",
    base: { sha: "base" },
    head: { sha: "head" },
  },
};

const brandedTitle =
  '# <img src="https://pipr.run/images/pipr/pipr-mark.svg" width="22" height="22" alt=""> Pipr Review';

describe("comments", () => {
  it("adapts inline publication to host capabilities", () => {
    const singleLine = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const multilineFinding = { ...finding, startLine: 10, endLine: 11 };
    const multiline = prepareInlinePublicationItems({
      validated: { validFindings: [multilineFinding] },
      manifest: manifestWithRange(10, 11, "fail()\nrecover()"),
      reviewedHeadSha: "head",
    });
    const plan = buildPublicationPlan({
      event,
      main: "Summary.",
      inlineItems: [...singleLine, ...multiline],
      reviewState: buildPriorReviewState({
        findings: [finding, multilineFinding],
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
      }),
      metadata: metadata(),
    });

    const adapted = publicationPlanForHostCapabilities(plan, {
      multilineInlineComments: false,
      suggestedChanges: false,
    });

    expect(adapted.inlineItems).toHaveLength(1);
    expect(adapted.inlineItems[0]?.finding.suggestedFix).toBeUndefined();
    expect(adapted.inlineItems[0]?.body).not.toContain("```suggestion");
    expect(adapted.inlineItems[0]?.body).toContain(
      "**Suggested change**\n\n```\nUse a safe call.\n```",
    );
  });

  it("renders one whole main comment body with review state", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.\n\nTests passed.",
      inlineItems: [],
      reviewState: buildPriorReviewState({
        findings: [finding],
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
      }),
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("<!-- pipr:main-comment change=1 version=1 state=");
    expect(plan.mainComment).toContain(
      `${brandedTitle}\n\n**Findings:** 1\n\nSummary body.\n\nTests passed.`,
    );
    expect(plan.mainComment).toContain(
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `head`.</sub>",
    );
    expect(plan.mainComment).not.toContain("pipr:contribution");
    expect(extractPriorReviewState(plan.mainComment, 1)?.findings[0]).not.toHaveProperty("body");
  });

  it("omits the built-in finding count when no findings survive validation", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: { ...metadata(), validFindings: 0 },
    });

    expect(plan.mainComment).toContain(`${brandedTitle}\n\nSummary body.`);
    expect(plan.mainComment).not.toContain("**Findings:**");
  });

  it("renders the main comment attribution with the short reviewed head SHA", () => {
    const plan = buildPublicationPlan({
      event: {
        change: {
          ...event.change,
          head: { sha: "abcdef1234567890" },
        },
      },
      main: "Summary body.",
      inlineItems: [],
      metadata: { ...metadata(), reviewedHeadSha: "abcdef1234567890" },
    });

    expect(plan.mainComment).toContain(
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `abcdef1`.</sub>",
    );
  });

  it("renders collapsed review stats before the attribution", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: ["anthropic/claude-sonnet", "openai/gpt-5"],
          agentRuns: 4,
          durationMs: 65_432,
          inputTokens: 1_234_567,
          outputTokens: 8_900,
          costUsd: 0.003_456,
          usageStatus: "complete" as const,
        },
      },
    });

    expect(plan.mainComment).toContain(
      [
        "<!-- pipr:stats:start -->",
        "<details>",
        "<summary>Review stats</summary>",
        "",
        "| Metric | Total |",
        "| --- | ---: |",
        "| Models | <code>anthropic/claude-sonnet</code>, <code>openai/gpt-5</code> |",
        "| Agent runs | 4 |",
        "| Elapsed | 1m 5.4s |",
        "| Input tokens | 1,234,567 |",
        "| Output tokens | 8,900 |",
        "| Cost (USD) | $0.0035 |",
        "",
        "</details>",
        "<!-- pipr:stats:end -->",
      ].join("\n"),
    );
    expect(plan.mainComment.indexOf("<!-- pipr:stats:start -->")).toBeLessThan(
      plan.mainComment.indexOf("<sub>Review generated by"),
    );
    expect(plan.mainComment).not.toContain("<details open>");
  });

  it("independently hides generated main comment presentation", () => {
    const options = {
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: ["openai/gpt-5"],
          agentRuns: 1,
          durationMs: 100,
          inputTokens: 10,
          outputTokens: 5,
          costUsd: 0.001,
          usageStatus: "complete" as const,
        },
      },
    };
    const withoutHeader = buildPublicationPlan({ ...options, showHeader: false });
    const withoutFooter = buildPublicationPlan({ ...options, showFooter: false });
    const withoutStats = buildPublicationPlan({ ...options, showStats: false });

    expect(withoutHeader.mainComment).not.toContain(mainCommentTitle);
    expect(withoutHeader.mainComment).toContain("Review generated by");
    expect(withoutFooter.mainComment).not.toContain("Review generated by");
    expect(withoutFooter.mainComment).toContain(mainCommentTitle);
    expect(withoutStats.mainComment).not.toContain("<summary>Review stats</summary>");
    expect(withoutStats.mainComment).toContain("<!-- pipr:main-comment ");
    expect(withoutStats.mainComment).toContain("Summary body.");
    expect(withoutStats.metadata.stats).toMatchObject({ agentRuns: 1 });
  });

  it("labels incomplete review usage without presenting missing data as zero", () => {
    const partial = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 2,
          durationMs: 500,
          inputTokens: 1_000,
          outputTokens: 100,
          costUsd: 0.002,
          usageStatus: "partial",
        },
      },
    });
    const unavailable = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 1,
          durationMs: 500,
          inputTokens: 0,
          outputTokens: 0,
          costUsd: 0,
          usageStatus: "unavailable",
        },
      },
    });

    expect(partial.mainComment).toContain("| Input tokens | 1,000 (reported) |");
    expect(partial.mainComment).toContain("| Cost (USD) | $0.0020 (reported) |");
    expect(unavailable.mainComment.match(/\| Unavailable \|/g)).toHaveLength(3);
    expect(unavailable.mainComment).not.toContain("| Cost (USD) | $0.00 |");
  });

  it("keeps reported model identifiers inside the stats table", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: [
            "router|model`variant\nlatest",
            "`leading",
            "trailing`",
            "``",
            "router\\|[review details](https://attacker.example)",
          ],
          agentRuns: 1,
          durationMs: 1,
          inputTokens: 1,
          outputTokens: 1,
          costUsd: 0,
          usageStatus: "complete",
        },
      },
    });

    expect(plan.mainComment).toContain(
      "| Models | <code>router&#124;model`variant latest</code>, <code>`leading</code>, <code>trailing`</code>, <code>``</code>, <code>router\\&#124;[review details](https://attacker.example)</code> |",
    );
    expect(plan.mainComment).not.toContain("\nlatest |");
    expect(plan.mainComment).not.toContain("](https://attacker.example) | ");
  });

  it("adds a footer notice when the config SDK pin is behind the runtime", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: { ...metadata(), configVersion: "0.1.0" },
    });

    expect(plan.mainComment).toContain(
      `<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit \`head\`. Config SDK 0.1.0 is behind [Pipr ${runtimeVersion}](https://github.com/somus/pipr/releases/tag/v${runtimeVersion}).</sub>`,
    );
  });

  it("omits the footer notice when the config SDK pin matches the runtime", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: { ...metadata(), configVersion: runtimeVersion },
    });

    expect(plan.mainComment).toContain(
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `head`.</sub>",
    );
    expect(plan.mainComment).not.toContain("Config SDK");
    expect(plan.mainComment).not.toContain("is behind Pipr");
  });

  it("strips versioned attribution from prior main comments", () => {
    for (const attribution of [
      `<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit \`head\`. Config SDK 0.1.0 is behind Pipr ${runtimeVersion}.</sub>`,
      `<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit \`head\`. Config SDK 0.1.0 is behind [Pipr ${runtimeVersion}](https://github.com/somus/pipr/releases/tag/v${runtimeVersion}).</sub>`,
    ]) {
      const priorMainComment = [brandedTitle, "", "Prior summary.", "", attribution].join("\n");

      expect(priorReviewForTask(priorMainComment, undefined).main).toBe("Prior summary.");
    }
  });

  it("strips Pipr review stats from prior main comment context", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Prior summary.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        validFindings: 0,
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 1,
          durationMs: 1_250,
          inputTokens: 500,
          outputTokens: 50,
          costUsd: 0.001,
          usageStatus: "complete",
        },
      },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe("Prior summary.");
  });

  it("strips Pipr review stats when the attribution footer is hidden", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Prior summary.",
      inlineItems: [],
      showFooter: false,
      metadata: {
        ...metadata(),
        validFindings: 0,
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 1,
          durationMs: 1_250,
          inputTokens: 500,
          outputTokens: 50,
          costUsd: 0.001,
          usageStatus: "complete",
        },
      },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe("Prior summary.");
  });

  it("preserves a task-authored Pipr heading when the generated header is hidden", () => {
    const main = "# Pipr Review\n\nTask-authored summary.";
    const plan = buildPublicationPlan({
      event,
      main,
      inlineItems: [],
      showHeader: false,
      metadata: { ...metadata(), validFindings: 0 },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
  });

  it("preserves a task-authored hidden-header marker", () => {
    const main = "<!-- pipr:header:hidden -->\n# Pipr Review\n\nTask-authored summary.";
    const plan = buildPublicationPlan({
      event,
      main,
      inlineItems: [],
      metadata: { ...metadata(), validFindings: 0 },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
  });

  it("preserves a hidden-header marker in a markerless prior comment", () => {
    const main = "Task-authored summary.\n<!-- pipr:header:hidden -->\nMore detail.";

    expect(priorReviewForTask(main, undefined).main).toBe(main);
  });

  it("recognizes the generated header marker after leading separator lines", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Prior summary.",
      inlineItems: [],
      showHeader: false,
      metadata: { ...metadata(), validFindings: 0 },
    });
    const main = plan.mainComment.replace(
      "\n\n<!-- pipr:header:hidden -->",
      "\n\n\n<!-- pipr:header:hidden -->",
    );

    expect(priorReviewForTask(main, undefined).main).toBe("Prior summary.");
  });

  it("preserves a task-authored main-comment marker", () => {
    const main = "Prior summary.\n\n<!-- pipr:main-comment task-owned -->";
    const plan = buildPublicationPlan({
      event,
      main,
      inlineItems: [],
      metadata: { ...metadata(), validFindings: 0 },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
  });

  it("preserves a task-authored canonical stats block when no generated stats are rendered", () => {
    const main = [
      "Prior summary.",
      "",
      "<!-- pipr:stats:start -->",
      "<details>",
      "<summary>Review stats</summary>",
      "",
      "| Metric | Total |",
      "| --- | ---: |",
      "| Models | <code>deepseek-v4-pro</code> |",
      "| Agent runs | 1 |",
      "| Elapsed | 1.3s |",
      "| Input tokens | 500 |",
      "| Output tokens | 50 |",
      "| Cost (USD) | $0.0010 |",
      "",
      "</details>",
      "<!-- pipr:stats:end -->",
    ].join("\n");
    for (const presentation of [{ showStats: false }, { showFooter: false }]) {
      const plan = buildPublicationPlan({
        event,
        main,
        inlineItems: [],
        ...presentation,
        metadata: { ...metadata(), validFindings: 0 },
      });

      expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
    }
  });

  it("preserves task-authored attribution text when the generated footer is hidden", () => {
    const main = [
      "Prior summary.",
      "",
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `authored`.</sub>",
      "",
      "Task-authored tail.",
    ].join("\n");
    const stats = {
      models: ["deepseek-v4-pro"],
      agentRuns: 1,
      durationMs: 1_250,
      inputTokens: 500,
      outputTokens: 50,
      costUsd: 0.001,
      usageStatus: "complete" as const,
    };

    for (const metadataStats of [undefined, stats]) {
      const plan = buildPublicationPlan({
        event,
        main,
        inlineItems: [],
        showFooter: false,
        metadata: {
          ...metadata(),
          validFindings: 0,
          ...(metadataStats ? { stats: metadataStats } : {}),
        },
      });

      expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
    }
  });

  it("preserves stats marker text supplied by the Review Task", () => {
    const main = [
      "Prior summary.",
      "<!-- pipr:stats:start -->",
      "Caller-owned matched content.",
      "<!-- pipr:stats:end -->",
      "Still caller-owned.",
      "<!-- pipr:stats:start -->",
      "Caller-owned unmatched content.",
    ].join("\n");
    const plan = buildPublicationPlan({
      event,
      main,
      inlineItems: [],
      metadata: {
        ...metadata(),
        validFindings: 0,
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 1,
          durationMs: 1,
          inputTokens: 1,
          outputTokens: 1,
          costUsd: 0,
          usageStatus: "complete",
        },
      },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
  });

  it("preserves a task-owned noncanonical Review stats footer", () => {
    const main = [
      "Prior summary.",
      "",
      "<!-- pipr:stats:start -->",
      "<details>",
      "<summary>Review stats</summary>",
      "Task-owned custom telemetry.",
      "</details>",
      "<!-- pipr:stats:end -->",
    ].join("\n");
    const plan = buildPublicationPlan({
      event,
      main,
      inlineItems: [],
      metadata: { ...metadata(), validFindings: 0 },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe(main);
  });

  it("preserves bounded model identifiers in comments and metadata", () => {
    const credentials = [
      ["sk-proj-", "abcdefghijklmnopqrstuvwxyz123456"].join(""),
      ["sk_live_", "abcdefghijklmnopqrstuvwxyz123456"].join(""),
      ["ghp_", "abcdefghijklmnopqrstuvwxyz1234567890"].join(""),
      ["github_pat_", "abcdefghijklmnopqrstuvwxyz_1234567890"].join(""),
      ["ASIA", "ABCDEFGHIJKLMNOP"].join(""),
      "provider-abcdefghijklmnopqrstuvwxyz123456",
    ];
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        stats: {
          models: credentials,
          agentRuns: 1,
          durationMs: 1,
          inputTokens: 1,
          outputTokens: 1,
          costUsd: 0,
          usageStatus: "complete",
        },
      },
    });

    expect(plan.metadata.stats?.models).toEqual(credentials);
    for (const credential of credentials) {
      expect(plan.mainComment).toContain(credential);
    }
  });

  it("strips generated stats with scientific-notation cost from prior context", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Prior summary.",
      inlineItems: [],
      metadata: {
        ...metadata(),
        validFindings: 0,
        stats: {
          models: ["deepseek-v4-pro"],
          agentRuns: 1,
          durationMs: 1,
          inputTokens: 1,
          outputTokens: 1,
          costUsd: 1e21,
          usageStatus: "complete",
        },
      },
    });

    expect(priorReviewForTask(plan.mainComment, undefined).main).toBe("Prior summary.");
  });

  it("rejects review stats without a model", () => {
    expect(() =>
      buildPublicationPlan({
        event,
        main: "Summary body.",
        inlineItems: [],
        metadata: {
          ...metadata(),
          stats: {
            models: [],
            agentRuns: 1,
            durationMs: 1,
            inputTokens: 1,
            outputTokens: 1,
            costUsd: 0,
            usageStatus: "complete",
          },
        },
      }),
    ).toThrow();
  });

  it("replaces the visible main comment body wholesale", () => {
    const plan = buildPublicationPlan({
      event,
      main: "New summary.",
      inlineItems: [],
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("New summary.");
    expect(plan.mainComment).not.toContain("Old summary.");
  });

  it("preserves the visible main comment body", () => {
    const plan = buildPublicationPlan({
      event,
      main: "A hard-coded secret was committed: pipr_eval_secret_do_not_repeat_12345.",
      inlineItems: [],
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("pipr_eval_secret_do_not_repeat_12345");
  });

  it("dedupes inline drafts with hidden markers", () => {
    const first = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const existing = first[0];
    if (!existing) {
      throw new Error("test fixture missing inline item");
    }
    const second = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
      reviewState: {
        version: 1,
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
        findings: [
          {
            id: existing.findingId,
            status: "open",
            path: existing.path,
            rangeId: existing.finding.rangeId,
            side: existing.side,
            startLine: existing.startLine,
            endLine: existing.endLine,
            firstSeenHeadSha: "head",
            lastSeenHeadSha: "head",
            lastCommentedHeadSha: "head",
          },
        ],
      },
    });

    expect(first).toHaveLength(1);
    expect(second).toHaveLength(0);
    expect(extractInlineFindingMarkers(first.map((draft) => draft.body))).toEqual(
      new Set([`pipr:finding:${existing.findingId}:head`]),
    );
    expect(first[0]?.body).toContain("This can fail.");
    expect(first[0]?.body).toContain("**Issue**\n\nThis can fail.");
    expect(first[0]?.body).toContain(
      "**Suggested change**\n\n```suggestion\nUse a safe call.\n```",
    );
    expect(first[0]?.body).not.toContain("Suggested fix:");
  });

  it("does not wrap inline bodies that already start with structured markdown", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            body: "**High correctness:** This can fail.",
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.body).toContain("**High correctness:** This can fail.");
    expect(item?.body).not.toContain("**Issue**");
  });

  it("omits suggested-change blocks when suggestedFix is absent", () => {
    const findingWithoutSuggestion = { ...finding };
    delete findingWithoutSuggestion.suggestedFix;

    expectSuggestedChangeOmitted({ finding: findingWithoutSuggestion });
  });

  it("publishes suggested-change blocks when one selected line expands to multiple replacement lines", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            suggestedFix: ["if (failed) {", "  recover();", "}"].join("\n"),
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.finding.suggestedFix).toBe(["if (failed) {", "  recover();", "}"].join("\n"));
    expect(item?.body).toContain("This can fail.");
    expect(item?.body).toContain("```suggestion\nif (failed) {\n  recover();\n}\n```");
  });

  it("omits suggested-change blocks when a one-line selection keeps that line as context", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 5,
        endLine: 5,
        suggestedFix: [
          "  const value = user.name ?? user.displayName;",
          "  if (!value) {",
          '    return "Anonymous";',
          "  }",
          "  return value.trim();",
        ].join("\n"),
      },
      manifest: manifestWithRange(5, 5, "  return value.trim();"),
    });
  });

  it("preserves inline bodies and suggestions before Action publication redaction", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            body: "The literal pipr_eval_secret_do_not_repeat_12345 should not be repeated.",
            suggestedFix: 'const apiKey = "pipr_eval_secret_do_not_repeat_12345";',
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.finding.body).toContain("pipr_eval_secret_do_not_repeat_12345");
    expect(item?.finding.suggestedFix).toBe(
      'const apiKey = "pipr_eval_secret_do_not_repeat_12345";',
    );
    expect(item?.body).toContain("pipr_eval_secret_do_not_repeat_12345");
    expect(item?.body).toContain("```suggestion");
  });

  it("uses publishable inline finding bodies for marker IDs and review state", () => {
    const rawFinding = {
      ...finding,
      body: "The literal pipr_eval_secret_do_not_repeat_12345 should not be repeated.",
      suggestedFix: 'const apiKey = "pipr_eval_secret_do_not_repeat_12345";',
    };
    const [item] = prepareInlinePublicationItems({
      validated: { validFindings: [rawFinding] },
      manifest,
      reviewedHeadSha: "head",
    });
    if (!item) {
      throw new Error("test fixture missing inline item");
    }
    const plan = buildPublicationPlan({
      event,
      main: "Summary.",
      inlineItems: [item],
      metadata: metadata(),
    });
    const state = extractPriorReviewState(plan.mainComment, 1);
    if (!state) {
      throw new Error("test fixture missing review state");
    }
    const markedState = applyInlineFindingMarkers(state, [item.body]);

    expect(state.findings[0]?.id).toBe(item.findingId);
    expect(markedState.findings[0]?.lastCommentedHeadSha).toBe("head");
    expect(
      prepareInlinePublicationItems({
        validated: { validFindings: [rawFinding] },
        manifest,
        reviewedHeadSha: "head",
        reviewState: markedState,
      }),
    ).toHaveLength(0);
  });

  it("skips inline drafts when body normalization leaves no publishable text", () => {
    const items = prepareInlinePublicationItems({
      validated: {
        validFindings: [{ ...finding, body: "   \n\t   " }],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(items).toEqual([]);
  });

  it("publishes suggested-change blocks when a multi-line selection has a shorter replacement", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            endLine: 12,
            suggestedFix: "return safeCall();",
          },
        ],
      },
      manifest: manifestWithRange(10, 12, ["fail()", "recover()", "return"].join("\n")),
      reviewedHeadSha: "head",
    });

    expect(item?.finding.suggestedFix).toBe("return safeCall();");
    expect(item?.body).toContain("This can fail.");
    expect(item?.body).toContain("```suggestion\nreturn safeCall();\n```");
  });

  it("omits broad suggested-change blocks while keeping the finding", () => {
    const selectedLines = [
      "---",
      'title: "Changelog"',
      'description: "Release history for Pipr."',
      "---",
      "",
      "This changelog is generated from Conventional Commits by Release Please.",
      "",
      "## 0.2.2 (2026-07-06)",
      "",
      "### Features",
      "",
      "- harden review prompts and evals",
      ...Array.from({ length: 42 }, (_, index) => `release line ${index}`),
    ];
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 1,
        endLine: selectedLines.length,
        suggestedFix: [
          "---",
          'title: "Changelog"',
          'description: "Release history for Pipr."',
          "---",
          "",
          "For the full release history, see CHANGELOG.md.",
        ].join("\n"),
      },
      manifest: manifestWithRange(1, selectedLines.length, selectedLines.join("\n")),
    });
  });

  it("omits suggested-change blocks when the selected preview is unavailable", () => {
    expectSuggestedChangeOmitted({
      manifest: {
        ...manifest,
        files: manifest.files.map((file) => ({
          ...file,
          commentableRanges: file.commentableRanges.map((range) => ({
            ...range,
            preview: undefined,
          })),
        })),
      },
    });
  });

  it("omits suggested-change blocks for left-side findings", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        side: "LEFT",
        suggestedFix: "safeCall();",
      },
      manifest: {
        ...manifest,
        files: manifest.files.map((file) => ({
          ...file,
          commentableRanges: file.commentableRanges.map((range) => ({
            ...range,
            side: "LEFT",
            kind: "deleted",
          })),
        })),
      },
    });
  });

  it("omits suggested-change blocks when the replacement includes unchanged edge lines", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        endLine: 14,
        suggestedFix: [
          "const next = compute();",
          "if (next < 0) {",
          "  return 0;",
          "}",
          "return next;",
        ].join("\n"),
      },
      manifest: manifestWithRange(
        10,
        14,
        ["const next = compute();", "if (next < 0) {", "  return next;", "}", "return next;"].join(
          "\n",
        ),
      ),
    });
  });

  it("omits suggested-change blocks when the replacement only drops a trailing blank line", () => {
    const selectedLines = [
      "const state = findState();",
      'if (state === "MERGED") {',
      '  console.log("already merged");',
      "  return;",
      "}",
      "",
    ];

    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 25,
        suggestedFix: selectedLines.slice(0, -1).join("\n"),
      },
      manifest: manifestWithRange(20, 25, selectedLines.join("\n")),
    });
  });

  it("omits suggested-change blocks when the replacement is identical to the selected lines", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "return value;",
      },
      manifest: manifestWithRange(20, 20, "return value;"),
    });
  });

  it("omits suggested-change blocks when the replacement only changes indentation", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "    return value;",
      },
      manifest: manifestWithRange(20, 20, "  return value;"),
    });
  });

  it("omits suggested-change blocks when the replacement only changes internal whitespace", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "return  value;",
      },
      manifest: manifestWithRange(20, 20, "return value;"),
    });
  });

  it("omits formatting-only suggestions when literals contain comment-like syntax", () => {
    for (const [preview, suggestedFix] of [
      ['const endpoint = "https://example.com";', 'const  endpoint = "https://example.com";'],
      ["const pattern = /[/*]/;", "const  pattern = /[/*]/;"],
    ]) {
      expectSuggestedChangeOmitted({
        finding: {
          ...finding,
          startLine: 20,
          endLine: 20,
          suggestedFix,
        },
        manifest: manifestWithRange(20, 20, preview),
      });
    }
  });

  it("publishes suggested-change blocks when whitespace changes inside a literal", () => {
    for (const [preview, suggestedFix] of [
      ['const header = "Bearer" + token;', 'const header = "Bearer " + token;'],
      ["const label = `hello$" + "{name}`;", "const label = `hello $" + "{name}`;"],
      ["const pattern = /ab/;", "const pattern = /a b/;"],
      ["return /ab/;", "return /a b/;"],
      ["returnvalue;", "return value;"],
      ["if (ok) /ab/.test(value);", "if (ok) /a b/.test(value);"],
      ["// Join firstand last name", "// Join first and last name"],
    ]) {
      const [item] = prepareInlinePublicationItems({
        validated: {
          validFindings: [
            {
              ...finding,
              startLine: 20,
              endLine: 20,
              suggestedFix,
            },
          ],
        },
        manifest: manifestWithRange(20, 20, preview),
        reviewedHeadSha: "head",
      });

      expect(item?.finding.suggestedFix).toBe(suggestedFix);
    }
  });

  it("omits suggested-change blocks for whitespace-only template expression edits", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "const label = `$" + "{first+last}`;",
      },
      manifest: manifestWithRange(20, 20, "const label = `$" + "{first + last}`;"),
    });
  });

  it("omits suggested-change blocks when the replacement invents an environment key", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "const apiKey = process.env.PIPR_NEW_API_KEY;",
      },
      manifest: manifestWithRange(20, 20, 'const apiKey = "";'),
    });
  });

  it("omits suggested-change blocks when the replacement invents optional environment access", () => {
    for (const suggestedFix of [
      "const apiKey = process.env?.PIPR_NEW_API_KEY;",
      'const apiKey = process.env?.["PIPR_NEW_API_KEY"];',
      "const apiKey = Bun.env?.PIPR_NEW_API_KEY;",
      "const apiKey = import.meta.env?.PIPR_NEW_API_KEY;",
    ]) {
      expectSuggestedChangeOmitted({
        finding: {
          ...finding,
          startLine: 20,
          endLine: 20,
          suggestedFix,
        },
        manifest: manifestWithRange(20, 20, 'const apiKey = "";'),
      });
    }
  });

  it("omits suggested-change blocks when the replacement invents destructured environment access", () => {
    for (const suggestedFix of [
      "const { PIPR_NEW_API_KEY } = process.env;",
      "const { PIPR_NEW_API_KEY: apiKey } = Bun.env;",
      'const { PIPR_NEW_API_KEY = "" } = import.meta.env;',
    ]) {
      expectSuggestedChangeOmitted({
        finding: {
          ...finding,
          startLine: 20,
          endLine: 20,
          suggestedFix,
        },
        manifest: manifestWithRange(20, 20, 'const apiKey = "";'),
      });
    }
  });

  it("publishes suggested-change blocks when the environment key already exists nearby", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            startLine: 20,
            endLine: 20,
            suggestedFix: "const apiKey = process.env.PIPR_API_KEY?.trim();",
          },
        ],
      },
      manifest: manifestWithRange(20, 20, "const apiKey = process.env.PIPR_API_KEY;"),
      reviewedHeadSha: "head",
    });

    expect(item?.finding.suggestedFix).toBe("const apiKey = process.env.PIPR_API_KEY?.trim();");
  });

  it("omits suggested-change blocks when a structural selection edge is replaced", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 60,
        endLine: 61,
        suggestedFix:
          "    if (code === 0x1b && cursor + 1 < message.length && message.charCodeAt(cursor + 1) === 0x5c) {",
      },
      manifest: manifestWithRange(60, 61, ["  }", "  return message.length - 1;"].join("\n")),
    });
  });

  it("omits suggested-change blocks when an opening structural edge is replaced", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 60,
        endLine: 61,
        suggestedFix: ["  }", "  return message.length;"].join("\n"),
      },
      manifest: manifestWithRange(60, 61, ["  {", "  return message.length - 1;"].join("\n")),
    });
  });

  it("omits suggested-change blocks when an angle structural edge is replaced", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 60,
        endLine: 61,
        suggestedFix: ["  >", "  return message.length;"].join("\n"),
      },
      manifest: manifestWithRange(60, 61, ["  <", "  return message.length - 1;"].join("\n")),
    });
  });

  it("publishes suggested-change blocks when a structural edge keeps the same delimiter", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            suggestedFix: "};",
          },
        ],
      },
      manifest: manifestWithRange(10, 10, "}"),
      reviewedHeadSha: "head",
    });

    expect(item?.finding.suggestedFix).toBe("};");
    expect(item?.body).toContain("```suggestion\n};\n```");
  });

  it("omits suggested-change blocks when a one-line selection includes surrounding context", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 11,
        endLine: 11,
        suggestedFix: [
          "const adjusted = priceCents - 100;",
          "return Math.max(0, adjusted);",
          "}",
        ].join("\n"),
      },
      manifest: manifestWithRange(
        10,
        12,
        ["export function finalPrice(priceCents: number): number {", "return adjusted;", "}"].join(
          "\n",
        ),
      ),
    });
  });

  it("preserves the complete inline finding body during publication", () => {
    const secondParagraph = "This second paragraph must remain published.";
    const body = `${"The actionable issue is concise. ".repeat(40)}\n\n${secondParagraph}`;
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            body,
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.finding.body).toBe(body);
    expect(item?.body).toContain(body);
  });

  it("uses a longer suggestion fence when replacement code contains backticks", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [{ ...finding, suggestedFix: 'const fence = "```";' }],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.body).toContain('````suggestion\nconst fence = "```";\n````');
  });

  it("preserves a renamed file's previous path through publication assembly", () => {
    const renamed: DiffManifest = {
      ...manifest,
      files: manifest.files.map((file) => ({
        ...file,
        path: "src/new.ts",
        previousPath: "src/old.ts",
        status: "renamed",
        commentableRanges: file.commentableRanges.map((range) => ({
          ...range,
          path: "src/new.ts",
        })),
      })),
    };
    const [item] = prepareInlinePublicationItems({
      validated: { validFindings: [{ ...finding, path: "src/new.ts" }] },
      manifest: renamed,
      reviewedHeadSha: "head",
    });

    expect(item).toMatchObject({ path: "src/new.ts", previousPath: "src/old.ts" });
  });

  it("republishes inline drafts when the same-head inline comment was deleted", () => {
    const first = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const existing = first[0];
    if (!existing) {
      throw new Error("test fixture missing inline item");
    }
    const state = applyInlineFindingMarkers(
      {
        version: 1,
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
        findings: [
          {
            id: existing.findingId,
            status: "open",
            path: existing.path,
            rangeId: existing.finding.rangeId,
            side: existing.side,
            startLine: existing.startLine,
            endLine: existing.endLine,
            firstSeenHeadSha: "head",
            lastSeenHeadSha: "head",
            lastCommentedHeadSha: "head",
          },
        ],
      },
      [],
    );

    expect(state.findings[0]?.lastCommentedHeadSha).toBeUndefined();
    expect(
      prepareInlinePublicationItems({
        validated: { validFindings: [finding] },
        manifest,
        reviewedHeadSha: "head",
        reviewState: state,
      }),
    ).toHaveLength(1);
  });
});

function metadata() {
  return {
    runtimeVersion,
    reviewedHeadSha: "head",
    providerModels: ["deepseek-v4-pro"],
    selectedTasks: ["review"],
    failedTasks: [],
    validFindings: 1,
    droppedFindings: 0,
  };
}

function expectSuggestedChangeOmitted(
  options: { finding?: ReviewFinding; manifest?: DiffManifest } = {},
): void {
  const [item] = prepareInlinePublicationItems({
    validated: { validFindings: [options.finding ?? finding] },
    manifest: options.manifest ?? manifest,
    reviewedHeadSha: "head",
  });

  expect(item?.finding.suggestedFix).toBeUndefined();
  expect(item?.body).toContain("This can fail.");
  expect(item?.body).not.toContain("```suggestion");
}

function manifestWithRange(startLine: number, endLine: number, preview = "fail()"): DiffManifest {
  return {
    ...manifest,
    files: manifest.files.map((file) => ({
      ...file,
      commentableRanges: file.commentableRanges.map((range) => ({
        ...range,
        startLine,
        endLine,
        preview,
      })),
    })),
  };
}
