import { describe, expect, it } from "bun:test";
import { runtimeVersion } from "../../shared/version.js";
import type { DiffManifest, ReviewFinding } from "../../types.js";
import {
  buildPublicationPlan,
  prepareInlinePublicationItems,
  publicationPlanForHostCapabilities,
} from "../comment.js";
import {
  applyInlineFindingMarkers,
  buildPriorReviewState,
  extractInlineFindingMarkers,
  extractPriorReviewState,
} from "../prior-state.js";

const finding: ReviewFinding = {
  body: "This can fail.",
  path: "src/a.ts",
  rangeId: "range-1",
  side: "RIGHT",
  startLine: 10,
  endLine: 10,
  suggestedFix: "Use a safe call.",
};

const manifest: DiffManifest = {
  baseSha: "base",
  headSha: "head",
  mergeBaseSha: "base",
  files: [
    {
      path: "src/a.ts",
      status: "modified",
      additions: 1,
      deletions: 0,
      hunks: [
        {
          hunkIndex: 1,
          header: "@@ -10,1 +10,1 @@",
          oldStart: 10,
          oldLines: 1,
          newStart: 10,
          newLines: 1,
          contentHash: "deadbeefcafe",
        },
      ],
      commentableRanges: [
        {
          id: "range-1",
          path: "src/a.ts",
          side: "RIGHT",
          startLine: 10,
          endLine: 10,
          kind: "added",
          hunkIndex: 1,
          hunkHeader: "@@ -10,1 +10,1 @@",
          hunkContentHash: "deadbeefcafe",
          preview: "fail()",
        },
      ],
    },
  ],
};

const event = {
  change: {
    number: 1,
    title: "",
    description: "",
    base: { sha: "base" },
    head: { sha: "head" },
  },
};

describe("comments", () => {
  it("adapts inline publication to host capabilities", () => {
    const singleLine = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const multilineFinding = { ...finding, startLine: 10, endLine: 11 };
    const multiline = prepareInlinePublicationItems({
      validated: { validFindings: [multilineFinding] },
      manifest: manifestWithRange(10, 11, "fail()\nrecover()"),
      reviewedHeadSha: "head",
    });
    const plan = buildPublicationPlan({
      event,
      main: "Summary.",
      inlineItems: [...singleLine, ...multiline],
      reviewState: buildPriorReviewState({
        findings: [{ finding }, { finding: multilineFinding }],
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
      }),
      metadata: metadata(),
    });

    const adapted = publicationPlanForHostCapabilities(plan, {
      multilineInlineComments: false,
      suggestedChanges: false,
    });

    expect(adapted.inlineItems).toHaveLength(1);
    expect(adapted.inlineItems[0]?.finding.suggestedFix).toBeUndefined();
    expect(adapted.inlineItems[0]?.body).not.toContain("```suggestion");
    expect(adapted.inlineItems[0]?.body).toContain(
      "**Suggested change**\n\n```\nUse a safe call.\n```",
    );
  });

  it("renders one whole main comment body with review state", () => {
    const plan = buildPublicationPlan({
      event,
      main: "Summary body.\n\nTests passed.",
      inlineItems: [],
      reviewState: buildPriorReviewState({
        findings: [{ finding }],
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
      }),
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("<!-- pipr:main-comment change=1 version=1 state=");
    expect(plan.mainComment).toContain(
      "> ⚠️ **Needs attention:** 1 actionable finding was identified.",
    );
    expect(plan.mainComment).toContain("Summary body.\n\nTests passed.");
    expect(plan.mainComment).toContain(
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `head`.</sub>",
    );
    expect(plan.mainComment).not.toContain("pipr:contribution");
    expect(extractPriorReviewState(plan.mainComment, 1)?.findings[0]).not.toHaveProperty("body");
  });

  it("replaces the visible main comment body wholesale", () => {
    const plan = buildPublicationPlan({
      event,
      main: "New summary.",
      inlineItems: [],
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("New summary.");
    expect(plan.mainComment).not.toContain("Old summary.");
  });

  it("preserves the visible main comment body", () => {
    const plan = buildPublicationPlan({
      event,
      main: "A hard-coded secret was committed: pipr_eval_secret_do_not_repeat_12345.",
      inlineItems: [],
      metadata: metadata(),
    });

    expect(plan.mainComment).toContain("pipr_eval_secret_do_not_repeat_12345");
  });

  it("dedupes inline drafts with hidden markers", () => {
    const first = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const existing = first[0];
    if (!existing) {
      throw new Error("test fixture missing inline item");
    }
    const second = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
      reviewState: {
        version: 1,
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
        findings: [
          {
            id: existing.findingId,
            status: "open",
            path: existing.path,
            rangeId: existing.finding.rangeId,
            side: existing.side,
            startLine: existing.startLine,
            endLine: existing.endLine,
            firstSeenHeadSha: "head",
            lastSeenHeadSha: "head",
            lastCommentedHeadSha: "head",
          },
        ],
      },
    });

    expect(first).toHaveLength(1);
    expect(second).toHaveLength(0);
    expect(extractInlineFindingMarkers(first.map((draft) => draft.body))).toEqual(
      new Set([`pipr:finding:${existing.findingId}:head`]),
    );
    expect(first[0]?.body).toContain("This can fail.");
    expect(first[0]?.body).toContain("**Issue**\n\nThis can fail.");
    expect(first[0]?.body).toContain(
      "**Suggested change**\n\n```suggestion\nUse a safe call.\n```",
    );
    expect(first[0]?.body).not.toContain("Suggested fix:");
  });

  it("does not wrap inline bodies that already start with structured markdown", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            body: "**High correctness:** This can fail.",
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.body).toContain("**High correctness:** This can fail.");
    expect(item?.body).not.toContain("**Issue**");
  });

  it("omits suggested-change blocks when suggestedFix is absent", () => {
    const findingWithoutSuggestion = { ...finding };
    delete findingWithoutSuggestion.suggestedFix;

    expectSuggestedChangeOmitted({ finding: findingWithoutSuggestion });
  });

  it("publishes suggested-change blocks when one selected line expands to multiple replacement lines", () => {
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            suggestedFix: ["if (failed) {", "  recover();", "}"].join("\n"),
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.finding.suggestedFix).toBe(["if (failed) {", "  recover();", "}"].join("\n"));
    expect(item?.body).toContain("This can fail.");
    expect(item?.body).toContain("```suggestion\nif (failed) {\n  recover();\n}\n```");
  });

  it("omits broad suggested-change blocks while keeping the finding", () => {
    const selectedLines = [
      "---",
      'title: "Changelog"',
      'description: "Release history for Pipr."',
      "---",
      "",
      "This changelog is generated from Conventional Commits by Release Please.",
      "",
      "## 0.2.2 (2026-07-06)",
      "",
      "### Features",
      "",
      "- harden review prompts and evals",
      ...Array.from({ length: 42 }, (_, index) => `release line ${index}`),
    ];
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 1,
        endLine: selectedLines.length,
        suggestedFix: [
          "---",
          'title: "Changelog"',
          'description: "Release history for Pipr."',
          "---",
          "",
          "For the full release history, see CHANGELOG.md.",
        ].join("\n"),
      },
      manifest: manifestWithRange(1, selectedLines.length, selectedLines.join("\n")),
    });
  });

  it("omits suggested-change blocks when the replacement invents an environment key", () => {
    expectSuggestedChangeOmitted({
      finding: {
        ...finding,
        startLine: 20,
        endLine: 20,
        suggestedFix: "const apiKey = process.env.PIPR_NEW_API_KEY;",
      },
      manifest: manifestWithRange(20, 20, 'const apiKey = "";'),
    });
  });

  it("omits formatting-only suggestions when literals contain comment-like syntax", () => {
    for (const [preview, suggestedFix] of [
      ['const endpoint = "https://example.com";', 'const  endpoint = "https://example.com";'],
      ["const pattern = /[/*]/;", "const  pattern = /[/*]/;"],
    ]) {
      expectSuggestedChangeOmitted({
        finding: {
          ...finding,
          startLine: 20,
          endLine: 20,
          suggestedFix,
        },
        manifest: manifestWithRange(20, 20, preview),
      });
    }
  });

  it("preserves the complete inline finding body during publication", () => {
    const secondParagraph = "This second paragraph must remain published.";
    const body = `${"The actionable issue is concise. ".repeat(40)}\n\n${secondParagraph}`;
    const [item] = prepareInlinePublicationItems({
      validated: {
        validFindings: [
          {
            ...finding,
            body,
          },
        ],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(item?.finding.body).toBe(body);
    expect(item?.body).toContain(body);
  });

  it("preserves a renamed file's previous path through publication assembly", () => {
    const renamed: DiffManifest = {
      ...manifest,
      files: manifest.files.map((file) => ({
        ...file,
        path: "src/new.ts",
        previousPath: "src/old.ts",
        status: "renamed",
        commentableRanges: file.commentableRanges.map((range) => ({
          ...range,
          path: "src/new.ts",
        })),
      })),
    };
    const [item] = prepareInlinePublicationItems({
      validated: { validFindings: [{ ...finding, path: "src/new.ts" }] },
      manifest: renamed,
      reviewedHeadSha: "head",
    });

    expect(item).toMatchObject({ path: "src/new.ts", previousPath: "src/old.ts" });
  });

  it("republishes inline drafts when the same-head inline comment was deleted", () => {
    const first = prepareInlinePublicationItems({
      validated: { validFindings: [finding] },
      manifest,
      reviewedHeadSha: "head",
    });
    const existing = first[0];
    if (!existing) {
      throw new Error("test fixture missing inline item");
    }
    const state = applyInlineFindingMarkers(
      {
        version: 1,
        reviewedHeadSha: "head",
        selectedTasks: ["review"],
        findings: [
          {
            id: existing.findingId,
            status: "open",
            path: existing.path,
            rangeId: existing.finding.rangeId,
            side: existing.side,
            startLine: existing.startLine,
            endLine: existing.endLine,
            firstSeenHeadSha: "head",
            lastSeenHeadSha: "head",
            lastCommentedHeadSha: "head",
          },
        ],
      },
      [],
    );

    expect(state.findings[0]?.lastCommentedHeadSha).toBeUndefined();
    expect(
      prepareInlinePublicationItems({
        validated: { validFindings: [finding] },
        manifest,
        reviewedHeadSha: "head",
        reviewState: state,
      }),
    ).toHaveLength(1);
  });

  it("uses publishable inline finding bodies for marker IDs and review state", () => {
    const rawFinding = {
      ...finding,
      body: "The literal pipr_eval_secret_do_not_repeat_12345 should not be repeated.",
      suggestedFix: 'const apiKey = "pipr_eval_secret_do_not_repeat_12345";',
    };
    const [item] = prepareInlinePublicationItems({
      validated: { validFindings: [rawFinding] },
      manifest,
      reviewedHeadSha: "head",
    });
    if (!item) {
      throw new Error("test fixture missing inline item");
    }
    const plan = buildPublicationPlan({
      event,
      main: "Summary.",
      inlineItems: [item],
      metadata: metadata(),
    });
    const state = extractPriorReviewState(plan.mainComment, 1);
    if (!state) {
      throw new Error("test fixture missing review state");
    }
    const markedState = applyInlineFindingMarkers(state, [item.body]);

    expect(state.findings[0]?.id).toBe(item.findingId);
    expect(markedState.findings[0]?.lastCommentedHeadSha).toBe("head");
    expect(
      prepareInlinePublicationItems({
        validated: { validFindings: [rawFinding] },
        manifest,
        reviewedHeadSha: "head",
        reviewState: markedState,
      }),
    ).toHaveLength(0);
  });

  it("skips inline drafts when body normalization leaves no publishable text", () => {
    const items = prepareInlinePublicationItems({
      validated: {
        validFindings: [{ ...finding, body: "   \n\t   " }],
      },
      manifest,
      reviewedHeadSha: "head",
    });

    expect(items).toEqual([]);
  });
});

function metadata() {
  return {
    runtimeVersion,
    reviewedHeadSha: "head",
    providerModels: ["deepseek-v4-pro"],
    selectedTasks: ["review"],
    failedTasks: [],
    validFindings: 1,
    droppedFindings: 0,
  };
}

function expectSuggestedChangeOmitted(
  options: { finding?: ReviewFinding; manifest?: DiffManifest } = {},
): void {
  const [item] = prepareInlinePublicationItems({
    validated: { validFindings: [options.finding ?? finding] },
    manifest: options.manifest ?? manifest,
    reviewedHeadSha: "head",
  });

  expect(item?.finding.suggestedFix).toBeUndefined();
  expect(item?.body).toContain("This can fail.");
  expect(item?.body).not.toContain("```suggestion");
}

function manifestWithRange(startLine: number, endLine: number, preview = "fail()"): DiffManifest {
  return {
    ...manifest,
    files: manifest.files.map((file) => ({
      ...file,
      commentableRanges: file.commentableRanges.map((range) => ({
        ...range,
        startLine,
        endLine,
        preview,
      })),
    })),
  };
}
