import { describe, expect, it } from "bun:test";
import {
  mainCommentFooterHiddenMarker,
  mainCommentHeaderHiddenMarker,
  reviewStatsEndMarker,
  reviewStatsStartMarker,
} from "../comment-branding.js";
import { parseGeneratedMainCommentEnvelope } from "../main-comment-envelope.js";

describe("parseGeneratedMainCommentEnvelope", () => {
  it("does not recognize a header marker without the main marker", () => {
    const envelope = parseGeneratedMainCommentEnvelope([mainCommentHeaderHiddenMarker, "body"]);

    expect(envelope.mainMarkerIndex).toBe(-1);
    expect(envelope.headerMarkerIndex).toBe(-1);
  });

  it("recognizes generated hidden and attribution footers", () => {
    const hidden = parseGeneratedMainCommentEnvelope(["body", mainCommentFooterHiddenMarker, ""]);
    const attribution = parseGeneratedMainCommentEnvelope([
      "body",
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `abc1234`.</sub>",
      "",
    ]);

    expect(hidden.footerIndex).toBe(1);
    expect(attribution.footerIndex).toBe(1);
  });

  it("recognizes a complete generated stats block without a trailing footer", () => {
    const lines = [
      "body",
      reviewStatsStartMarker,
      "<details>",
      "<summary>Review stats</summary>",
      "",
      "| Metric | Total |",
      "| --- | ---: |",
      "| Models | `model` |",
      "| Agent runs | 1 |",
      "| Elapsed | 1s |",
      "| Input tokens | 10 |",
      "| Output tokens | 5 |",
      "| Cost (USD) | $0.01 |",
      "",
      "</details>",
      reviewStatsEndMarker,
    ];

    expect(parseGeneratedMainCommentEnvelope(lines).statsRange).toEqual({ start: 1, end: 15 });
  });

  it("recognizes completion details with workflow run links", () => {
    const lines = [
      "body",
      reviewStatsStartMarker,
      "<details>",
      "<summary>📊 Review completed in 5m</summary>",
      "",
      "| Metric | Total |",
      "| --- | ---: |",
      "| Models | <code>model</code> |",
      "| Agent runs | 1 |",
      "| Elapsed | 5m |",
      "| Input tokens | 10 |",
      "| Output tokens | 5 |",
      "| Cost (USD) | $0.01 |",
      "| Workflow runs | [Run 1](<https://github.com/acme/repo/actions/runs/123>), [Run 2](<https://github.com/acme/repo/actions/runs/124>) |",
      "",
      "</details>",
      reviewStatsEndMarker,
    ];

    expect(parseGeneratedMainCommentEnvelope(lines).statsRange).toEqual({ start: 1, end: 16 });
  });
});
