import { describe, expect, it } from "bun:test";
import {
  extractReviewProgressToken,
  renderFailedReviewProgress,
  renderRunningReviewProgress,
  stripReviewProgress,
} from "../progress.js";

const options = {
  changeNumber: 42,
  token: "11111111-1111-4111-8111-111111111111",
  reviewedHeadSha: "abcdef1234567890",
  stage: "running-review-tasks" as const,
  showHeader: true,
  showFooter: true,
};

describe("review progress", () => {
  it("renders a minimal accessible first-run comment with a decorative image", () => {
    const body = renderRunningReviewProgress(options);

    expect(body).toContain("Pipr Review");
    expect(body).toContain("## Progress");
    expect(body).toContain(
      '<img src="https://pipr.run/images/pipr/review-progress-v1.gif" width="48" height="48" alt="">',
    );
    expect(body).toContain("<strong>Running: Running review tasks</strong>");
    expect(body).toContain("Pipr is reviewing commit `abcdef1`.");
    expect(body).not.toContain("Review generated by");
    expect(extractReviewProgressToken(body)).toBe(options.token);
  });

  it("preserves an existing review while replacing its progress block", () => {
    const prior = [
      "<!-- pipr:main-comment change=42 version=1 -->",
      "",
      "# Prior review",
      "",
      "Existing findings stay here.",
    ].join("\n");
    const first = renderRunningReviewProgress({
      ...options,
      body: prior,
      stage: "building-diff",
    });
    const second = renderRunningReviewProgress({
      ...options,
      body: first,
      stage: "validating-review",
    });

    expect(second.match(/## Progress/g)).toHaveLength(1);
    expect(second).toContain("Existing findings stay here.");
    expect(second.indexOf("## Progress")).toBeLessThan(
      second.indexOf("Existing findings stay here."),
    );
    expect(second).toContain("<strong>Running: Validating review</strong>");
    expect(stripReviewProgress(second)).toBe(prior);
  });

  it("retains a concise redacted failure and optional workflow details", () => {
    const running = renderRunningReviewProgress(options);
    const failed = renderFailedReviewProgress({
      ...options,
      body: running,
      durationMs: 301_000,
      reason: "provider <failed> | secret\nverbose stack",
      workflowUrl: "https://github.com/acme/repo/actions/runs/123",
      showStats: false,
    });

    expect(failed).toContain("<summary>Review failed after 5m 1s</summary>");
    expect(failed).toContain("**Failed stage:** Running review tasks");
    expect(failed).toContain("provider &lt;failed&gt; &#124; secret");
    expect(failed).not.toContain("verbose stack");
    expect(failed).toContain("[View workflow](<https://github.com/acme/repo/actions/runs/123>)");
    expect(failed).toContain("Pipr stopped while reviewing commit `abcdef1`.");
    expect(failed).not.toContain("| Metric | Total |");
  });
});
