import { describe, expect, it } from "bun:test";
import {
  extractReviewProgressToken,
  renderFailedReviewProgress,
  renderRunningReviewProgress,
  stripReviewProgress,
} from "../progress.js";
import { priorReviewForTask } from "../task/task-output.js";

const options = {
  changeNumber: 42,
  token: "11111111-1111-4111-8111-111111111111",
  reviewedHeadSha: "abcdef1234567890",
  stage: "running-review-tasks" as const,
  showHeader: true,
  showFooter: true,
  firstRun: true,
};

describe("review progress", () => {
  it("renders a minimal accessible first-run comment with a decorative image", () => {
    const body = renderRunningReviewProgress(options);

    expect(body).toContain("Pipr Review");
    expect(body).toContain("## Progress");
    expect(body).toContain(
      '<img src="https://pipr.run/images/pipr/review-progress-v1.gif" width="48" height="48" alt="">',
    );
    expect(body).toContain("<strong>Running: Running review tasks</strong>");
    expect(body).toContain("Pipr is reviewing commit `abcdef1`.");
    expect(body).not.toContain("Review generated by");
    expect(extractReviewProgressToken(body)).toBe(options.token);
  });

  it("preserves an existing review while replacing its progress block", () => {
    const prior = [
      "<!-- pipr:main-comment change=42 version=1 -->",
      "",
      "# Prior review",
      "",
      "Existing findings stay here.",
    ].join("\n");
    const first = renderRunningReviewProgress({
      ...options,
      body: prior,
      stage: "building-diff",
      firstRun: false,
    });
    const second = renderRunningReviewProgress({
      ...options,
      body: first,
      stage: "validating-review",
      firstRun: false,
    });

    expect(second.match(/## Progress/g)).toHaveLength(1);
    expect(second).toContain("Existing findings stay here.");
    expect(second.indexOf("## Progress")).toBeLessThan(
      second.indexOf("Existing findings stay here."),
    );
    expect(second).toContain("<strong>Running: Validating review</strong>");
    expect(stripReviewProgress(second)).toBe(prior);
  });

  it("keeps first-run progress out of prior review context", () => {
    const body = renderRunningReviewProgress(options);

    expect(priorReviewForTask(body, undefined).main).toBeUndefined();
  });

  it("preserves task-authored blank lines while progress is inserted and removed", () => {
    const prior = [
      "<!-- pipr:main-comment change=42 version=1 -->",
      "",
      "# Prior review",
      "",
      "```text",
      "first",
      "",
      "",
      "second",
      "```",
    ].join("\n");
    const running = renderRunningReviewProgress({
      ...options,
      body: prior,
      firstRun: false,
    });

    expect(stripReviewProgress(running)).toBe(prior);
    expect(running).toContain("first\n\n\nsecond");
  });

  it("retains a concise redacted failure and optional workflow details", () => {
    const running = renderRunningReviewProgress(options);
    const failed = renderFailedReviewProgress({
      ...options,
      body: running,
      durationMs: 301_000,
      reason: "provider <failed> & unstable | secret\nverbose stack",
      workflowUrl: "https://github.com/acme/repo/actions/runs/123",
      showStats: false,
    });

    expect(failed).toContain("<summary>Review failed after 5m 1s</summary>");
    expect(failed).toContain("**Failed stage:** Running review tasks");
    expect(failed).toContain("provider &lt;failed&gt; &amp; unstable &#124; secret");
    expect(failed).not.toContain("verbose stack");
    expect(failed).toContain("[View workflow](<https://github.com/acme/repo/actions/runs/123>)");
    expect(failed).toContain("Pipr stopped while reviewing commit `abcdef1`.");
    expect(failed).not.toContain("| Metric | Total |");
  });

  it("preserves unavailable usage in failed review stats", () => {
    const failed = renderFailedReviewProgress({
      ...options,
      durationMs: 1_000,
      reason: "provider failed",
      showStats: true,
      stats: {
        models: ["test/model"],
        agentRuns: 1,
        durationMs: 1_000,
        inputTokens: 0,
        outputTokens: 0,
        costUsd: 0,
        usageStatus: "unavailable",
      },
    });

    expect(failed.match(/\| Unavailable \|/g)).toHaveLength(3);
    expect(failed).not.toContain("(reported)");
  });
});
