import { describe, expect, it } from "bun:test";
import {
  extractReviewProgressToken,
  renderFailedReviewProgress,
  renderRunningReviewProgress,
  stripReviewProgress,
} from "../progress.js";
import { priorReviewForTask } from "../task/task-output.js";

const options = {
  changeNumber: 42,
  token: "11111111-1111-4111-8111-111111111111",
  reviewedHeadSha: "abcdef1234567890",
  stage: "running-review-tasks" as const,
  showHeader: true,
  showFooter: true,
  firstRun: true,
};

describe("review progress", () => {
  it("renders a minimal accessible first-run comment with a decorative image", () => {
    const body = renderRunningReviewProgress(options);

    expect(body).toContain("Pipr Review");
    expect(body).toContain("## Progress");
    expect(body).toContain(
      '<img src="https://pipr.run/images/pipr/review-progress-v1.gif" width="48" height="48" alt="">',
    );
    expect(body).toContain("<strong>Running: Running review tasks</strong>");
    expect(body).toContain("Pipr is reviewing commit `abcdef1`.");
    expect(body).not.toContain("Review generated by");
    expect(extractReviewProgressToken(body)).toBe(options.token);
  });

  it("distinguishes active tasks, reviewers, and shards beneath the stable stage", () => {
    const body = renderRunningReviewProgress({
      ...options,
      work: {
        tasks: [
          {
            id: "0",
            name: "review <core>",
            state: "running",
            reviewers: [
              {
                id: "0:0",
                name: "security & trust",
                state: "running",
                shard: { current: 2, total: 4 },
              },
              {
                id: "0:1",
                name: "maintainability",
                state: "running",
                shard: { current: 1, total: 4 },
              },
            ],
          },
        ],
        completedRuns: 6,
        activeReviewers: 2,
      },
    });

    expect(body).toContain("<strong>Running: Running review tasks</strong>");
    expect(body).toContain("Task: <code>review &lt;core&gt;</code>");
    expect(body).toContain("Reviewer: <code>security &amp; trust</code> · shard 2 of 4");
    expect(body).toContain("Reviewer: <code>maintainability</code> · shard 1 of 4");
    expect(body).toContain("6 review runs completed · 2 reviewers active");
    expect(body).not.toContain("review <core>");
    expect(body.indexOf("Task:")).toBeGreaterThan(body.indexOf("Running: Running review tasks"));
    expect(body.indexOf("○ Validating review")).toBeGreaterThan(body.indexOf("2 reviewers active"));
  });

  it("bounds concurrent reviewer rows and summarizes overflow", () => {
    const body = renderRunningReviewProgress({
      ...options,
      work: {
        tasks: [
          {
            id: "0",
            name: "review",
            state: "running",
            reviewers: Array.from({ length: 5 }, (_, index) => ({
              id: `0:${index}`,
              name: `reviewer-${index + 1}`,
              state: "running" as const,
              shard: { current: 1, total: 4 },
            })),
          },
        ],
        completedRuns: 0,
        activeReviewers: 5,
      },
    });

    expect(body.match(/Reviewer: /g)).toHaveLength(3);
    expect(body).toContain("+2 more reviewers active");
    expect(body).not.toContain("reviewer-4");
  });

  it("preserves an existing review while replacing its progress block", () => {
    const prior = [
      "<!-- pipr:main-comment change=42 version=1 -->",
      "",
      "# Prior review",
      "",
      "Existing findings stay here.",
    ].join("\n");
    const first = renderRunningReviewProgress({
      ...options,
      body: prior,
      stage: "building-diff",
      firstRun: false,
    });
    const second = renderRunningReviewProgress({
      ...options,
      body: first,
      stage: "validating-review",
      firstRun: false,
    });

    expect(second.match(/## Progress/g)).toHaveLength(1);
    expect(second).toContain("Existing findings stay here.");
    expect(second.indexOf("## Progress")).toBeLessThan(
      second.indexOf("Existing findings stay here."),
    );
    expect(second).toContain("<strong>Running: Validating review</strong>");
    expect(stripReviewProgress(second)).toBe(prior);
  });

  it("keeps first-run progress out of prior review context", () => {
    const body = renderRunningReviewProgress(options);

    expect(priorReviewForTask(body, undefined).main).toBeUndefined();
  });

  it("preserves task-authored blank lines while progress is inserted and removed", () => {
    const prior = [
      "<!-- pipr:main-comment change=42 version=1 -->",
      "",
      "# Prior review",
      "",
      "```text",
      "first",
      "",
      "",
      "second",
      "```",
    ].join("\n");
    const running = renderRunningReviewProgress({
      ...options,
      body: prior,
      firstRun: false,
    });

    expect(stripReviewProgress(running)).toBe(prior);
    expect(running).toContain("first\n\n\nsecond");
  });

  it("retains a concise redacted failure and optional workflow details", () => {
    const running = renderRunningReviewProgress(options);
    const failed = renderFailedReviewProgress({
      ...options,
      body: running,
      durationMs: 301_000,
      reason: "provider <failed> & unstable | secret\nverbose stack",
      workflowUrl: "https://github.com/acme/repo/actions/runs/123",
      showStats: false,
    });

    expect(failed).toContain("<summary>Review failed after 5m 1s</summary>");
    expect(failed).toContain("**Failed stage:** Running review tasks");
    expect(failed).toContain("provider &lt;failed&gt; &amp; unstable &#124; secret");
    expect(failed).not.toContain("verbose stack");
    expect(failed).toContain("[View workflow](<https://github.com/acme/repo/actions/runs/123>)");
    expect(failed).toContain("Pipr stopped while reviewing commit `abcdef1`.");
    expect(failed).not.toContain("| Metric | Total |");
  });

  it("retains the failed task, reviewer, and shard", () => {
    const failed = renderFailedReviewProgress({
      ...options,
      durationMs: 12_000,
      reason: "provider failed",
      showStats: false,
      work: {
        tasks: [
          {
            id: "0",
            name: "review <core>",
            state: "failed",
            reviewers: [
              {
                id: "0:0",
                name: "security & trust",
                state: "failed",
                shard: { current: 2, total: 4 },
              },
            ],
          },
        ],
        completedRuns: 1,
        activeReviewers: 0,
      },
    });

    expect(failed).toContain(
      "**Failed work:** Task <code>review &lt;core&gt;</code> · Reviewer <code>security &amp; trust</code> · shard 2 of 4",
    );
  });

  it("preserves backslash-prefixed markdown punctuation", () => {
    const failed = renderFailedReviewProgress({
      ...options,
      durationMs: 1_000,
      reason: String.raw`provider \*failed\*`,
      showStats: false,
    });

    expect(failed).toContain(String.raw`provider \\\*failed\\\*`);
  });

  it("preserves unavailable usage in failed review stats", () => {
    const failed = renderFailedReviewProgress({
      ...options,
      durationMs: 1_000,
      reason: "provider failed",
      showStats: true,
      stats: {
        models: ["test/model"],
        agentRuns: 1,
        durationMs: 1_000,
        inputTokens: 0,
        outputTokens: 0,
        costUsd: 0,
        usageStatus: "unavailable",
      },
    });

    expect(failed.match(/\| Unavailable \|/g)).toHaveLength(3);
    expect(failed).not.toContain("(reported)");
  });
});
