import { describe, expect, it } from "bun:test";
import type { TaskContext } from "@usepipr/sdk";
import { mainCommentTitle, piprRepositoryUrl } from "../comment-branding.js";
import type { RuntimeTaskCheckResult } from "../task/task-runtime.js";
import {
  askCommandInvocation,
  commandTaskPlan,
  config,
  defaultReviewAgent,
  defaultReviewPlan,
  finding,
  noFindingsPiResult,
  priorReviewStateForTasks,
  recordingCheckSink,
  replacingRedactor,
  reviewPiResult,
  runRuntime,
  singleTaskPlan,
  testPlan,
} from "./task-runtime-fixtures.js";

describe("runTaskRuntime: outputs, checks, and commands", () => {
  it("rejects multiple final comments across selected tasks", async () => {
    const plan = testPlan((pipr) => {
      const slow = pipr.task({
        name: "slow",
        async run(ctx) {
          await ctx.comment({ inlineFindings: [finding("slow", "range-1", 10)] });
        },
      });
      const fast = pipr.task({
        name: "fast",
        async run(ctx) {
          await ctx.comment({ inlineFindings: [finding("fast", "range-2", 20)] });
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task: slow });
      pipr.on.changeRequest({ actions: ["opened"], task: fast });
    });

    await expect(
      runRuntime({
        plan,
      }),
    ).rejects.toThrow(
      "ctx.comment(...) may be called once per selected run; received comments from 'slow' and 'fast'",
    );
  });

  it("caps inline findings from one final comment", async () => {
    const plan = testPlan((pipr) => {
      const task = pipr.task({
        name: "review",
        async run(ctx) {
          await ctx.comment({
            inlineFindings: [finding("slow", "range-1", 10), finding("fast", "range-2", 20)],
          });
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task });
    });

    const result = await runRuntime({
      config: { ...config, publication: { ...config.publication, maxInlineComments: 1 } },
      plan,
    });

    expect(result.publicationPlan.metadata.selectedTasks).toEqual(["review"]);
    expect(result.inlineCommentDrafts.map((item) => item.finding.body)).toEqual(["slow body"]);
  });

  it("applies main comment presentation settings without dropping stats metadata", async () => {
    const result = await runRuntime({
      config: {
        ...config,
        publication: {
          ...config.publication,
          showHeader: false,
          showFooter: false,
          showStats: false,
        },
      },
      plan: defaultReviewPlan(),
      piRunner: async () => reviewPiResult([]),
    });

    expect(result.mainComment).not.toContain(mainCommentTitle);
    expect(result.mainComment).not.toContain("Review generated by");
    expect(result.mainComment).not.toContain("<summary>Review stats</summary>");
    expect(result.publicationPlan.metadata.stats).toMatchObject({ agentRuns: 1 });
  });

  it("collects markdown and inline findings through ctx.comment", async () => {
    const plan = singleTaskPlan({
      async run(ctx) {
        await ctx.comment({
          main: "Review summary.",
          inlineFindings: [finding("inline", "range-1", 10)],
        });
      },
    });

    const result = await runRuntime({
      plan,
    });

    expect(result.mainComment).toContain("Review summary.");
    expect(result.review.summary.body).toBe("Review summary.");
    expect(result.validated.review.summary.body).toBe("Review summary.");
    expect(result.inlineCommentDrafts.map((item) => item.finding.body)).toEqual(["inline body"]);
  });

  it("redacts known runtime secrets before building the publication plan", async () => {
    const detected = "registered-runtime-secret";
    const plan = singleTaskPlan({
      async run(ctx) {
        await ctx.comment({
          main: `Review summary contains ${detected}.`,
          inlineFindings: [
            {
              ...finding("inline", "range-1", 10),
              body: `Inline body contains ${detected}.`,
              suggestedFix: `const value = "${detected}";`,
            },
            {
              ...finding("inline-duplicate", "range-1", 10),
              body: `Inline body contains ${detected}.`,
              suggestedFix: `const value = "${detected}";`,
            },
          ],
        });
      },
    });

    const result = await runRuntime({
      plan,
      secretRedactor: {
        addSecret() {},
        redact(value) {
          return {
            detected: value.includes(detected),
            value: value.replaceAll(detected, "[redacted secret]"),
          };
        },
      },
    });

    expect(result.publicationPlan.mainComment).toContain(
      "Review summary contains [redacted secret].",
    );
    expect(result.publicationPlan.inlineItems[0]?.finding).toMatchObject({
      body: "Inline body contains [redacted secret].",
    });
    expect(result.publicationPlan.inlineItems[0]?.finding).not.toHaveProperty("suggestedFix");
    expect(result.publicationPlan.inlineItems[0]?.body).not.toContain(detected);
    expect(result.validated.droppedFindings[0]?.finding).toMatchObject({
      body: "Inline body contains [redacted secret].",
    });
    expect(result.validated.droppedFindings[0]?.finding).not.toHaveProperty("suggestedFix");
  });

  it("uses string ctx.comment output as the review summary body", async () => {
    const plan = singleTaskPlan({
      async run(ctx) {
        await ctx.comment("String review summary.");
      },
    });

    const result = await runRuntime({
      plan,
    });

    expect(result.mainComment).toContain("String review summary.");
    expect(result.review.summary.body).toBe("String review summary.");
    expect(result.validated.review.summary.body).toBe("String review summary.");
  });

  it("records command replies from command-triggered tasks", async () => {
    let observedCommand: unknown;
    const plan = testPlan((pipr) => {
      const task = pipr.task<{ question: string }>({
        name: "ask",
        async run(ctx, input) {
          observedCommand = ctx.command;
          await ctx.command?.reply(`Answer: ${input.question}`);
        },
      });
      pipr.command({ pattern: "@pipr ask <question...>", permission: "read", task });
    });

    const result = await runRuntime({
      plan,
      taskName: "ask",
      taskInput: { question: "what changed?" },
      commandInvocation: askCommandInvocation(),
    });

    expect(observedCommand).toMatchObject({
      name: "ask",
      line: "@pipr ask what changed?",
      arguments: { question: "what changed?" },
    });
    expect(result).toMatchObject({
      kind: "command-response",
      commandResponse: {
        commandName: "ask",
        body: "Answer: what changed?",
      },
    });
    expect(result).not.toHaveProperty("publicationPlan");
    expect(result).not.toHaveProperty("review");
  });

  it("returns command run usage collected before the reply", async () => {
    const plan = testPlan((pipr) => {
      const agent = defaultReviewAgent(pipr);
      const task = pipr.task({
        name: "ask",
        async run(ctx) {
          await ctx.pi.run(agent, { manifest: await ctx.change.diffManifest() });
          await ctx.command?.reply("Answer.");
        },
      });
      pipr.command({ pattern: "@pipr ask <question...>", permission: "read", task });
    });
    const result = await runRuntime({
      plan,
      taskName: "ask",
      commandInvocation: askCommandInvocation(),
      piRunner: async () => ({
        ...noFindingsPiResult(),
        models: ["command-model"],
        usage: {
          status: "partial",
          inputTokens: 80,
          outputTokens: 8,
          costUsd: 0.0008,
        },
      }),
    });
    if (result.kind !== "command-response") {
      throw new Error(`expected command response, received ${result.kind}`);
    }

    expect(result.run).toMatchObject({
      trigger: "command",
      models: ["command-model"],
      agentRuns: 1,
      inputTokens: 80,
      outputTokens: 8,
      costUsd: 0.0008,
      usageStatus: "partial",
    });
  });

  it("redacts command replies before returning them for publication", async () => {
    const detected = "registered-runtime-secret";
    const result = await runRuntime({
      plan: commandTaskPlan(async (ctx) => {
        await ctx.command?.reply(`Answer contains ${detected}.`);
      }),
      taskName: "ask",
      taskInput: { question: "what changed?" },
      commandInvocation: askCommandInvocation(),
      secretRedactor: replacingRedactor(detected),
    });

    expect(result.commandResponse?.body).toBe("Answer contains [redacted secret].");
  });

  it("does not expose command context outside command-triggered tasks", async () => {
    let observedCommand: unknown = "unset";
    const plan = singleTaskPlan({
      async run(ctx) {
        observedCommand = ctx.command;
        await ctx.comment("Review summary.");
      },
    });

    await runRuntime({ plan });

    expect(observedCommand).toBeUndefined();
  });

  it("rejects tasks that emit both a review comment and a command reply", async () => {
    const plan = commandTaskPlan(async (ctx) => {
      await ctx.command?.reply("Answer.");
      await ctx.comment("Review summary.");
    });

    await expect(
      runRuntime({
        plan,
        taskName: "ask",
        taskInput: { question: "what changed?" },
        commandInvocation: askCommandInvocation(),
      }),
    ).rejects.toThrow("ctx.comment(...) and ctx.command.reply(...) cannot both be called");
  });

  it("rejects multiple command replies from one task", async () => {
    const plan = commandTaskPlan(async (ctx) => {
      await ctx.command?.reply("First.");
      await ctx.command?.reply("Second.");
    });

    await expect(
      runRuntime({
        plan,
        taskName: "ask",
        taskInput: { question: "what changed?" },
        commandInvocation: askCommandInvocation(),
      }),
    ).rejects.toThrow(
      "ctx.command.reply(...) may be called once per selected run; 'ask' called it more than once",
    );
  });

  it("rejects mixed review comments and command replies across selected tasks", async () => {
    const plan = testPlan((pipr) => {
      const ask = pipr.task({
        name: "ask",
        async run(ctx) {
          await ctx.command?.reply("Answer.");
        },
      });
      const review = pipr.task({
        name: "review",
        async run(ctx) {
          await ctx.comment("Review summary.");
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task: ask });
      pipr.on.changeRequest({ actions: ["opened"], task: review });
    });

    await expect(
      runRuntime({
        plan,
        commandInvocation: askCommandInvocation(),
      }),
    ).rejects.toThrow("ctx.comment(...) and ctx.command.reply(...) cannot both be called");
  });

  it("rejects multiple command replies across selected tasks", async () => {
    const plan = testPlan((pipr) => {
      const ask = pipr.task({
        name: "ask",
        async run(ctx) {
          await ctx.command?.reply("Ask answer.");
        },
      });
      const explain = pipr.task({
        name: "explain",
        async run(ctx) {
          await ctx.command?.reply("Explain answer.");
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task: ask });
      pipr.on.changeRequest({ actions: ["opened"], task: explain });
    });

    await expect(
      runRuntime({
        plan,
        commandInvocation: askCommandInvocation(),
      }),
    ).rejects.toThrow(
      "ctx.command.reply(...) may be called once per selected run; received replies from 'ask' and 'explain'",
    );
  });

  it("records explicit ctx.check outcomes without failing the review", async () => {
    const plan = testPlan((pipr) => {
      const task = pipr.task({
        name: "review",
        check: { name: "pipr / review" },
        async run(ctx) {
          ctx.check.fail("Security gate failed.");
          await ctx.comment("Review completed.");
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task });
    });

    const result = await runRuntime({ plan });

    expect(result.taskChecks).toEqual([
      { taskName: "review", conclusion: "failure", summary: "Security gate failed." },
    ]);
    expect(result.mainComment).toContain("Review completed.");
  });

  it("redacts task check summaries before exposing them to the check sink", async () => {
    const detected = "registered-runtime-secret";
    const outcomes: unknown[] = [];
    const plan = singleTaskPlan({
      check: { name: "pipr / review" },
      async run(ctx) {
        ctx.check.fail(`Security gate contains ${detected}.`);
        await ctx.comment("Review completed.");
      },
    });

    const result = await runRuntime({
      plan,
      checkSink: recordingCheckSink(outcomes),
      secretRedactor: replacingRedactor(detected),
    });

    const expected: RuntimeTaskCheckResult = {
      taskName: "review",
      conclusion: "failure",
      summary: "Security gate contains [redacted secret].",
    };
    expect(result.taskChecks).toEqual([expected]);
    expect(outcomes).toEqual([expected]);
  });

  it("rejects multiple ctx.check outcomes from one task", async () => {
    const outcomes: unknown[] = [];
    const plan = singleTaskPlan({
      check: { name: "pipr / review" },
      async run(ctx) {
        ctx.check.pass("Done.");
        ctx.check.fail("Too late.");
        await ctx.comment("Review completed.");
      },
    });

    await expect(
      runRuntime({
        plan,
        checkSink: recordingCheckSink(outcomes),
      }),
    ).rejects.toThrow("ctx.check may be completed at most once per task");
    expect(outcomes).toEqual([
      {
        taskName: "review",
        conclusion: "failure",
        summary: "Task failed; see logs for details.",
      },
    ]);
  });

  it("publishes failed task checks when a task throws", async () => {
    const outcomes: unknown[] = [];
    const plan = singleTaskPlan({
      check: { name: "pipr / review" },
      async run(ctx) {
        ctx.check.pass("Started.");
        throw new Error("Task failed.");
      },
    });

    await expect(
      runRuntime({
        plan,
        checkSink: recordingCheckSink(outcomes),
      }),
    ).rejects.toThrow("Task failed.");
    expect(outcomes).toEqual([
      { taskName: "review", conclusion: "failure", summary: "Task failed; see logs for details." },
    ]);
  });

  it("rejects multiple ctx.comment calls from one task", async () => {
    const plan = testPlan((pipr) => {
      const task = pipr.task({
        name: "review",
        async run(ctx) {
          await ctx.comment("First.");
          await ctx.comment("Second.");
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task });
    });

    await expect(runRuntime({ plan })).rejects.toThrow(
      "ctx.comment(...) may be called once per selected run; 'review' called it more than once",
    );
  });

  it("rejects selected tasks that do not emit a final comment", async () => {
    const plan = testPlan((pipr) => {
      const task = pipr.task({ name: "review", run() {} });
      pipr.on.changeRequest({ actions: ["opened"], task });
    });

    await expect(runRuntime({ plan })).rejects.toThrow(
      "ctx.comment(...) must be called exactly once per selected run",
    );
  });

  it("exposes prior review state through ctx.review.prior", async () => {
    let observedPrior: Awaited<ReturnType<TaskContext["review"]["prior"]>> | undefined;
    const priorMainComment = [
      "<!-- pipr:main-comment change=1 version=1 state=bad -->",
      "",
      mainCommentTitle,
      "",
      "Old review summary.",
      "",
      `<sub>Review generated by [Pipr](${piprRepositoryUrl}) for commit \`head\`.</sub>`,
    ].join("\n");
    const plan = testPlan((pipr) => {
      const task = pipr.task({
        name: "review",
        async run(ctx) {
          observedPrior = await ctx.review.prior();
          await ctx.comment("New review summary.");
        },
      });
      pipr.on.changeRequest({ actions: ["opened"], task });
    });

    const result = await runRuntime({
      plan,
      priorMainComment,
      priorReviewState: priorReviewStateForTasks(["review"]),
    });

    expect(result.mainComment).not.toContain("Old review summary.");
    expect(result.mainComment).toContain("New review summary.");
    expect(observedPrior).toEqual({
      main: "Old review summary.",
      reviewedHeadSha: "head",
      inlineFindings: [
        {
          id: "fnd_existing",
          status: "open",
          path: "src/a.ts",
          rangeId: "range-1",
          side: "RIGHT",
          startLine: 10,
          endLine: 10,
        },
      ],
    });
  });
});
