import { describe, expect, it } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildPublicationPlan, type InlinePublicationItem } from "../../../review/comment.js";
import { buildPriorReviewState, renderInlineFindingMarker } from "../../../review/prior-state.js";
import { priorReviewForTask } from "../../../review/task/task-output.js";
import type { ChangeRequestEventContext } from "../../../types.js";
import {
  type CodeHostAdapterConformanceHarness,
  defineCodeHostAdapterConformanceSuite,
} from "../../tests/conformance.js";
import type { CodeHostStatusState, RepositoryPermission } from "../../types.js";
import { createBitbucketHostAdapter } from "../adapter.js";
import type { BitbucketClient, BitbucketComment, BitbucketPullRequest } from "../client.js";
import { normalizeBitbucketMarkdown, renderBitbucketMarkdown } from "../markdown.js";

describe("Bitbucket Cloud adapter", () => {
  it("publishes idempotent main, multiline inline, commands, resolution, and statuses", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });
    const plan = publicationPlan();
    expect(await adapter.publication?.publish({ change, plan })).toMatchObject({
      mainComment: { action: "created" },
      inlineComments: { posted: 1 },
    });
    expect(await adapter.publication?.publish({ change, plan })).toMatchObject({
      mainComment: { action: "updated" },
      inlineComments: { skipped: 1 },
    });
    expect(client.createdBodies[1]).toMatchObject({
      inline: { path: "src/a.ts", to: 4, start_to: 2 },
    });
    const command = { change, sourceCommentId: "9", commandName: "ask", body: "answer" };
    await expect(adapter.publication?.publishCommandResponse?.(command)).resolves.toMatchObject({
      action: "created",
    });
    await expect(
      adapter.publication?.publishCommandResponse?.({ ...command, body: "updated" }),
    ).resolves.toMatchObject({ action: "updated" });
    const inline = client.comments.find((comment) => comment.inline);
    if (!inline) throw new Error("Expected inline comment");
    const action = {
      kind: "resolve" as const,
      findingId: "finding-1",
      findingHeadSha: "head",
      commentId: inline.id,
      threadId: inline.id,
      body: "resolved marker",
      responseKey: "resolved marker",
    };
    await adapter.publication?.publishThreadActions?.({
      change,
      actions: [action],
      reviewedHeadSha: "head",
    });
    await adapter.publication?.publishThreadActions?.({
      change,
      actions: [action],
      reviewedHeadSha: "head",
    });
    expect(client.comments.filter((comment) => comment.parent?.id === inline.id)).toHaveLength(1);
    expect(inline.resolution).toBeDefined();
    await expect(
      adapter.statuses?.upsert({ change, name: "review", state: "success" }),
    ).resolves.toEqual({ id: "pipr-review", name: "review" });
    expect(client.statusBodies[0]).toMatchObject({ state: "SUCCESSFUL", refname: "feature" });
    for (const comment of client.comments) {
      expect(comment.content.raw).not.toContain("<!--");
      expect(comment.content.raw).not.toMatch(/<\/?[A-Za-z][^>]*>/);
    }
  });

  it("publishes Markdown-only comments while preserving hidden publication metadata", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });
    const plan = publicationPlan();
    const inlineItem = plan.inlineItems[0];
    if (!inlineItem) throw new Error("Expected inline fixture");
    inlineItem.body = [
      renderInlineFindingMarker(inlineItem.findingId, inlineItem.reviewedHeadSha),
      "Fix",
      "",
      "<details>",
      "<summary>Rationale</summary>",
      "",
      "The retry can duplicate a delivery.",
      "",
      "</details>",
    ].join("\n");

    await adapter.publication?.publish({ change, plan });

    const published = client.createdBodies.map((body) => (body.content as { raw: string }).raw);
    expect(published).toHaveLength(2);
    for (const body of published) {
      expect(body).not.toContain("<!--");
      expect(body).not.toMatch(/<\/?[A-Za-z][^>]*>/);
      expect(body).toContain("[pipr-metadata-");
    }
    expect(published[0]).toContain("# Pipr Review");
    expect(published[1]).toContain("### Rationale");

    await expect(adapter.publication?.publish({ change, plan })).resolves.toMatchObject({
      mainComment: { action: "updated" },
      inlineComments: { skipped: 1 },
    });
  });

  it("removes the generated attribution from prior Markdown-only comments", () => {
    const canonical = [
      "Prior summary.",
      "",
      "<sub>Review generated by [Pipr](https://github.com/somus/pipr) for commit `head`.</sub>",
    ].join("\n");
    const published = renderBitbucketMarkdown(canonical);

    expect(published).not.toContain("<sub>");
    expect(priorReviewForTask(normalizeBitbucketMarkdown(published), undefined).main).toBe(
      "Prior summary.",
    );
  });

  it("fails stale endpoints before writes and declares native limits", async () => {
    const client = new FakeBitbucketClient();
    client.pullRequest = {
      ...client.pullRequest,
      source: { ...client.pullRequest.source, commit: { hash: "new-head" } },
    };
    const adapter = createBitbucketHostAdapter({ client });
    await expect(adapter.publication?.publish({ change, plan: publicationPlan() })).rejects.toThrow(
      "endpoints changed",
    );
    expect(client.comments).toEqual([]);
    expect(adapter.capabilities).toEqual({
      commandComments: true,
      reviewCommentReplies: true,
      threadResolution: true,
      multilineInlineComments: true,
      suggestedChanges: false,
      statuses: true,
    });
  });

  it("rejects a missing authenticated UUID before publication writes", async () => {
    const client = new FakeBitbucketClient();
    client.currentUserUuid = undefined;
    const adapter = createBitbucketHostAdapter({ client });

    await expect(adapter.publication?.publish({ change, plan: publicationPlan() })).rejects.toThrow(
      "authenticated user UUID is required",
    );
    expect(client.createdBodies).toEqual([]);
    expect(client.comments).toEqual([]);
  });

  it("publishes multiline LEFT-side comments against the previous path", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });
    const plan = publicationPlan();
    const item = plan.inlineItems[0];
    if (!item) throw new Error("Expected inline fixture");
    plan.inlineItems = [
      {
        ...item,
        finding: { ...item.finding, path: "src/old.ts", side: "LEFT" },
        range: { ...item.range, path: "src/old.ts", side: "LEFT", kind: "deleted" },
        path: "src/new.ts",
        previousPath: "src/old.ts",
        side: "LEFT",
      },
    ];

    await adapter.publication?.publish({ change, plan });

    expect(client.createdBodies[1]).toMatchObject({
      inline: { path: "src/old.ts", from: 4, start_from: 2 },
    });
  });

  it("loads prior review state with one user and comment request", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });
    await adapter.publication?.publish({ change, plan: publicationPlan() });
    client.currentUserCalls = 0;
    client.listCommentsCalls = 0;

    await expect(adapter.comments?.loadPriorReviewState?.({ change })).resolves.toBeDefined();
    expect(client.currentUserCalls).toBe(1);
    expect(client.listCommentsCalls).toBe(1);
  });

  it("retries only inline comments missing after partial publication", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });
    const plan = publicationPlan();
    const first = plan.inlineItems[0];
    if (!first) throw new Error("Expected inline fixture");
    const second = {
      ...first,
      finding: { ...first.finding, body: "Second fix", startLine: 5, endLine: 5 },
      range: { ...first.range, startLine: 5, endLine: 5 },
      startLine: 5,
      endLine: 5,
      findingId: "finding-2",
      marker: "pipr:finding:finding-2:head",
      body: `${renderInlineFindingMarker("finding-2", "head")}\nSecond fix`,
    };
    plan.inlineItems = [first, second];
    client.failCommentBodyOnce = "finding-2";

    await expect(adapter.publication?.publish({ change, plan })).rejects.toThrow(
      "Bitbucket inline comment publication failed",
    );
    await expect(adapter.publication?.publish({ change, plan })).resolves.toMatchObject({
      mainComment: { action: "updated" },
      inlineComments: { posted: 1, skipped: 1, failed: 0 },
    });

    expect(client.createdBodies.filter((body) => body.inline)).toHaveLength(2);
    expect(
      client.createdBodies.filter((body) => (body.inline as { to?: number } | undefined)?.to === 4),
    ).toHaveLength(1);
    expect(
      client.createdBodies.filter((body) => (body.inline as { to?: number } | undefined)?.to === 5),
    ).toHaveLength(1);
  });

  it("upserts a pending status to success with the same key", async () => {
    const client = new FakeBitbucketClient();
    const adapter = createBitbucketHostAdapter({ client });

    await adapter.statuses?.upsert({ change, name: "review", state: "pending" });
    await adapter.statuses?.upsert({ change, name: "review", state: "success" });

    expect(client.statusKeys).toEqual(["pipr-review", "pipr-review"]);
    expect(client.statusBodies).toMatchObject([
      { state: "INPROGRESS", refname: "feature" },
      { state: "SUCCESSFUL", refname: "feature" },
    ]);
  });
});

defineCodeHostAdapterConformanceSuite({
  name: "Bitbucket Cloud",
  createHarness: createBitbucketConformanceHarness,
});

const change: ChangeRequestEventContext = {
  eventName: "pullrequest:updated",
  platform: { id: "bitbucket" },
  repository: { slug: "workspace/repository" },
  coordinates: {
    provider: "bitbucket",
    workspace: "workspace",
    repository: "repository",
    repositoryUuid: "{repo}",
  },
  change: {
    number: 7,
    title: "PR",
    description: "",
    url: "https://bitbucket.org/workspace/repository/pull-requests/7",
    base: { sha: "base", ref: "main" },
    head: { sha: "head", ref: "feature" },
  },
  workspace: "/workspace",
};

function publicationPlan() {
  const item: InlinePublicationItem = {
    finding: {
      body: "Fix",
      path: "src/a.ts",
      rangeId: "range-1",
      side: "RIGHT",
      startLine: 2,
      endLine: 4,
    },
    range: {
      id: "range-1",
      path: "src/a.ts",
      side: "RIGHT",
      startLine: 2,
      endLine: 4,
      kind: "added",
      hunkIndex: 1,
      hunkHeader: "@@ -1 +1,4 @@",
      hunkContentHash: "deadbeefcafe",
    },
    path: "src/a.ts",
    side: "RIGHT",
    startLine: 2,
    endLine: 4,
    findingId: "finding-1",
    reviewedHeadSha: "head",
    marker: "pipr:finding:finding-1:head",
    body: `${renderInlineFindingMarker("finding-1", "head")}\nFix`,
  };
  return buildPublicationPlan({
    event: change,
    main: "Summary",
    inlineItems: [item],
    reviewState: buildPriorReviewState({
      findings: [item.finding],
      reviewedHeadSha: "head",
      selectedTasks: ["review"],
    }),
    metadata: {
      runtimeVersion: "0.4.0",
      reviewedHeadSha: "head",
      selectedTasks: ["review"],
      failedTasks: [],
      validFindings: 1,
      droppedFindings: 0,
    },
  });
}

class FakeBitbucketClient implements BitbucketClient {
  workspace = "workspace";
  repository = "repository";
  comments: BitbucketComment[] = [];
  createdBodies: Array<Record<string, unknown>> = [];
  statusBodies: Array<Record<string, unknown>> = [];
  statusKeys: string[] = [];
  failCommentBodyOnce: string | undefined;
  currentUserCalls = 0;
  listCommentsCalls = 0;
  permission: RepositoryPermission = "write";
  permissionActors: string[] = [];
  failInline = false;
  mainCreates = 0;
  mainUpdates = 0;
  commandCreates = 0;
  commandUpdates = 0;
  resolutionWrites = 0;
  normalizedStatusWrites: Array<{
    name: string;
    state: CodeHostStatusState;
    summary?: string;
    headSha: string;
  }> = [];
  afterListComments?: () => void;
  currentUserUuid: string | undefined = "{bot}";
  pullRequest: BitbucketPullRequest = {
    id: 7,
    title: "PR",
    description: "",
    source: endpoint("head", "feature"),
    destination: endpoint("base", "main"),
    links: { html: { href: "https://bitbucket.org/workspace/repository/pull-requests/7" } },
  };
  currentUser = async () => {
    this.currentUserCalls += 1;
    return { uuid: this.currentUserUuid, nickname: "pipr" };
  };
  getRepository = async () => ({
    uuid: "{repo}",
    slug: "repository",
    fullName: "workspace/repository",
    url: "https://bitbucket.org/workspace/repository",
  });
  getRepositoryPermission = async (actor: string) => {
    this.permissionActors.push(actor);
    return this.permission;
  };
  getPullRequest = async () => this.pullRequest;
  loadChange = async () => ({
    repository: change.repository,
    coordinates: change.coordinates as NonNullable<typeof change.coordinates>,
    change: change.change,
  });
  listComments = async () => {
    this.listCommentsCalls += 1;
    const comments = this.comments;
    this.afterListComments?.();
    return comments;
  };
  createComment = async (_id: number, body: Record<string, unknown>) => {
    if (
      this.failCommentBodyOnce &&
      normalizeBitbucketMarkdown((body.content as { raw?: string }).raw ?? "").includes(
        this.failCommentBodyOnce,
      )
    ) {
      this.failCommentBodyOnce = undefined;
      throw new Error("controlled Bitbucket comment failure");
    }
    if (body.inline && this.failInline) {
      this.failInline = false;
      throw new Error("Bitbucket rejected the inline comment");
    }
    this.createdBodies.push(body);
    const content = body.content as { raw: string };
    const normalizedContent = normalizeBitbucketMarkdown(content.raw);
    if (!body.inline && !body.parent) {
      if (normalizedContent.includes("pipr:command-response")) this.commandCreates += 1;
      else this.mainCreates += 1;
    }
    const comment: BitbucketComment = {
      id: String(this.comments.length + 1),
      content,
      user: { uuid: "{bot}", nickname: "pipr" },
      inline: body.inline as BitbucketComment["inline"],
      parent: body.parent as BitbucketComment["parent"],
    };
    this.comments.push(comment);
    return comment;
  };
  updateComment = async (_id: number, commentId: string, content: string) => {
    const comment = this.comments.find((item) => item.id === commentId);
    if (!comment) throw new Error("missing");
    comment.content.raw = content;
    if (normalizeBitbucketMarkdown(content).includes("pipr:command-response")) {
      this.commandUpdates += 1;
    } else this.mainUpdates += 1;
    return comment;
  };
  replyToComment = async (id: number, commentId: string, content: string) =>
    this.createComment(id, { content: { raw: content }, parent: { id: commentId } });
  resolveComment = async (_id: number, commentId: string) => {
    const comment = this.comments.find((item) => item.id === commentId);
    if (comment) {
      comment.resolution = { type: "resolution" };
      this.resolutionWrites += 1;
    }
  };
  setStatus = async (sha: string, key: string, body: Record<string, unknown>) => {
    this.statusKeys.push(key);
    this.statusBodies.push(body);
    const nativeState = String(body.state);
    const state: CodeHostStatusState =
      nativeState === "SUCCESSFUL"
        ? "success"
        : nativeState === "FAILED"
          ? "failure"
          : nativeState === "STOPPED"
            ? "neutral"
            : "pending";
    this.normalizedStatusWrites.push({
      name: key.replace(/^pipr-/, ""),
      state,
      ...(body.description ? { summary: String(body.description) } : {}),
      headSha: sha,
    });
    return key;
  };
}

async function createBitbucketConformanceHarness(): Promise<CodeHostAdapterConformanceHarness> {
  const root = await mkdtemp(path.join(os.tmpdir(), "pipr-bitbucket-conformance-"));
  const client = new FakeBitbucketClient();
  const adapter = createBitbucketHostAdapter({ client });
  const repository = {
    uuid: "{repo}",
    name: "repository",
    full_name: "workspace/repository",
    slug: "repository",
    links: { html: { href: "https://bitbucket.org/workspace/repository" } },
  };
  return {
    adapter,
    change,
    async events() {
      const eventPath = path.join(root, "event.json");
      const options = {
        eventPath,
        env: { BITBUCKET_EVENT_KEY: "pullrequest:created" },
        workspace: root,
      };
      await Bun.write(
        eventPath,
        JSON.stringify({ actor: { nickname: "developer" }, repository, pullrequest: { id: 7 } }),
      );
      const changeRequest = await adapter.events.parseEvent(options);
      await Bun.write(
        eventPath,
        JSON.stringify({
          actor: { nickname: "developer" },
          repository,
          pullrequest: { id: 7 },
          comment: { id: 101, content: { raw: "@pipr review" } },
        }),
      );
      const command = await adapter.events.parseEvent({
        ...options,
        env: { BITBUCKET_EVENT_KEY: "pullrequest:comment_created" },
      });
      await Bun.write(
        eventPath,
        JSON.stringify({
          actor: { nickname: "developer" },
          repository,
          pullrequest: { id: 7 },
          comment: { id: 102, parent: { id: 101 }, content: { raw: "Fixed." } },
        }),
      );
      const reply = await adapter.events.parseEvent({
        ...options,
        env: { BITBUCKET_EVENT_KEY: "pullrequest:comment_created" },
      });
      await Bun.write(
        eventPath,
        JSON.stringify({
          actor: { nickname: "developer" },
          repository,
          pullrequest: { id: 7, draft: true },
        }),
      );
      const draft = await adapter.events.parseEvent({
        ...options,
        env: { BITBUCKET_EVENT_KEY: "pullrequest:updated" },
      });
      return { changeRequest, command, reply, draft };
    },
    setPermission(permission) {
      client.permission = permission;
    },
    permissionRequests: () => client.permissionActors.map((actor) => ({ actor })),
    setCurrentHead(headSha) {
      client.pullRequest = {
        ...client.pullRequest,
        source: { ...client.pullRequest.source, commit: { hash: headSha } },
      };
    },
    advanceHeadDuringPreflight() {
      client.afterListComments = () => {
        client.afterListComments = undefined;
        client.pullRequest = {
          ...client.pullRequest,
          source: { ...client.pullRequest.source, commit: { hash: "new-head" } },
        };
      };
    },
    failNextInline() {
      client.failInline = true;
    },
    seedForeignInline() {
      client.comments.push({
        id: "foreign-inline",
        content: { raw: `${renderInlineFindingMarker("foreign", "head")}\nForeign.` },
        user: { uuid: "{developer}", nickname: "developer" },
        inline: { path: "src/new.ts", to: 4, start_to: 2 },
      });
    },
    seedForeignReply(body) {
      const root = client.comments.find(
        (comment) => comment.inline && comment.user?.uuid === "{bot}",
      );
      if (!root) throw new Error("Bitbucket conformance thread not found");
      client.comments.push({
        id: "foreign-reply",
        content: { raw: body },
        user: { uuid: "{developer}", nickname: "developer" },
        parent: { id: root.id },
      });
    },
    ownedReplyBodies: () =>
      client.comments
        .filter((comment) => comment.parent && comment.user?.uuid === "{bot}")
        .map((comment) => normalizeBitbucketMarkdown(comment.content.raw)),
    writes: () => ({
      mainCreates: client.mainCreates,
      mainUpdates: client.mainUpdates,
      inlineCreates: client.comments.filter(
        (comment) => comment.inline && comment.user?.uuid === "{bot}",
      ).length,
      commandCreates: client.commandCreates,
      commandUpdates: client.commandUpdates,
      replies: client.comments.filter((comment) => comment.parent && comment.user?.uuid === "{bot}")
        .length,
      resolutions: client.resolutionWrites,
    }),
    anchors: () => client.comments.filter((comment) => comment.inline).map(observedBitbucketAnchor),
    statuses: () => client.normalizedStatusWrites,
    dispose: () => rm(root, { recursive: true, force: true }),
  };
}

function observedBitbucketAnchor(comment: BitbucketComment) {
  const inline = comment.inline;
  if (!inline) throw new Error("Expected inline comment");
  if (inline.to != null) {
    return {
      path: "src/new.ts",
      side: "RIGHT" as const,
      startLine: inline.start_to ?? inline.to,
      endLine: inline.to,
      headSha: "head",
    };
  }
  return {
    path: "src/new.ts",
    previousPath: inline.path,
    side: "LEFT" as const,
    startLine: inline.start_from ?? inline.from ?? 0,
    endLine: inline.from ?? 0,
    headSha: "head",
  };
}

function endpoint(hash: string, branch: string) {
  return {
    branch: { name: branch },
    commit: { hash },
    repository: {
      uuid: "{repo}",
      name: "repository",
      slug: "repository",
      full_name: "workspace/repository",
      links: { html: { href: "https://bitbucket.org/workspace/repository" } },
    },
  };
}
